#!/usr/bin/env python3

class noora:
	def __init__(self, name, color, number):
		self.name = name
		self.color = color
		self.number = number

	def billycats(self):
		return f" my {self.number} cat name is {self.name} and its color is {self.color}"

cat1 = noora("noora1", "gray", "first")
cat2 = noora("naya", "black", "second")

print(cat1.billycats())
print(cat2.billycats())


